export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCHING_MOVIES = 'FETCHING_MOVIES';
export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID';

export const FETCH_MOVIE_TICKETS = 'FETCH_MOVIE_TICKETS';
export const FETCHING_MOVIE_TICKETS = 'FETCHING_MOVIE_TICKETS';