export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIE_TICKETS = 'FETCH_MOVIE_TICKETS';
export const CREATE_MOVIE_TICKETS = 'CREATE_MOVIE_TICKETS';
export const CALCULATE_MOVIE_TICKET_VALUE = 'CALCULATE_MOVIE_TICKET_VALUE';
